# app/config/installer.yml

pimcore_install:
    parameters:
        database_credentials:
            user:                 symfony
            password:             symfony
            dbname:               symfony
            
            # env variables can be directly read with the %env() syntax
            # see https://symfony.com/blog/new-in-symfony-3-2-runtime-environment-variables
            host:                 env(DB_HOST)
            port:                 env(DB_PORT)